language: python

sudo: false

matrix:
  include:
  - python: "2.6"
  - python: "2.7"
  - python: "3.3"
  - python: "3.4"
  - python: "3.5"
    env: BUILD_DOCS=yes

script:
  - python --version

deploy:
  provider: script
  script: script/pushdocs.sh
  skip_cleanup: true
  on:
    branch: master
    condition: $BUILD_DOCS=yes
